version: '2'

services:
  app:
#    container_name: 'authentication'
    image: 'authentication'
    build: ./
    depends_on:
      - db
    ports:
      - '8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/registration
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=registration

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "5000:5000"
